CREATE TABLE tms_role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    permissions VARCHAR(1024) NOT NULL
);

CREATE TABLE tms_todo (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    complete    BOOLEAN NOT NULL
);

CREATE TABLE tms_user (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id  BIGINT,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES tms_role(id)
);

INSERT INTO tms_role (name, permissions) VALUES
                                             ('ROLE_ADMIN', 'CREATE,READ,UPDATE,DELETE'),
                                             ('ROLE_MANAGER', 'CREATE,READ,UPDATE'),
                                             ('ROLE_USER', 'READ');